/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
   
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println(Module.status);

        if (Module.tipoRol.equals("ALMACENERO")) {
            itemRoles.setEnabled(false);
            itemUsuarios.setEnabled(false);
        }

        lblUsuarios.setText(Module.userName);

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        itemRoles = new javax.swing.JMenuItem();
        itemUsuarios = new javax.swing.JMenuItem();
        mnuGestion = new javax.swing.JMenu();
        itemMarcas = new javax.swing.JMenuItem();
        itemModelos = new javax.swing.JMenuItem();
        itemAutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuSistema = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        mnuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        mnuAdministracion.setText("ADMINISTACION");

        itemRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestion-de-equipos.png"))); // NOI18N
        itemRoles.setText("ROLES");
        itemRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRolesActionPerformed(evt);
            }
        });
        mnuAdministracion.add(itemRoles);

        itemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/grupo.png"))); // NOI18N
        itemUsuarios.setText("USUARIOS");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        mnuAdministracion.add(itemUsuarios);

        jMenuBar1.add(mnuAdministracion);

        mnuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Gestion30.png"))); // NOI18N
        mnuGestion.setText("GESTION ");

        itemMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/marca-registrada.png"))); // NOI18N
        itemMarcas.setText("Marcas");
        itemMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMarcasActionPerformed(evt);
            }
        });
        mnuGestion.add(itemMarcas);

        itemModelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/flujo-de-datos.png"))); // NOI18N
        itemModelos.setText("Modelos");
        itemModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModelosActionPerformed(evt);
            }
        });
        mnuGestion.add(itemModelos);

        itemAutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/coche.png"))); // NOI18N
        itemAutos.setText("Autos");
        itemAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutosActionPerformed(evt);
            }
        });
        mnuGestion.add(itemAutos);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestion-de-equipos.png"))); // NOI18N
        jMenuItem1.setText("Clientes");
        mnuGestion.add(jMenuItem1);

        jMenuBar1.add(mnuGestion);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte.png"))); // NOI18N
        mnuReportes.setText("REPORTES");
        jMenuBar1.add(mnuReportes);

        mnuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/salir_1.png"))); // NOI18N
        mnuSistema.setText("SISTEMA");

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancelar.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        mnuSistema.add(itemSalir);

        jMenuBar1.add(mnuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(823, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRolesActionPerformed

        FrmListadoRoles form = new FrmListadoRoles();

        form.toFront();
        form.setVisible(true);

    }//GEN-LAST:event_itemRolesActionPerformed

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed

        FrmListadoUsuarios usuarios = new FrmListadoUsuarios();
        usuarios.setVisible(true);
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void itemMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMarcasActionPerformed
        FrmListadoMarcas marcas = new FrmListadoMarcas();
        marcas.setVisible(true);
    }//GEN-LAST:event_itemMarcasActionPerformed

    private void itemModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModelosActionPerformed

        FrmListadoModelos modelos = new FrmListadoModelos();
        modelos.setVisible(true);
    }//GEN-LAST:event_itemModelosActionPerformed

    private void itemAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutosActionPerformed
        FrmListadoAutos modelos = new FrmListadoAutos();
        modelos.setVisible(true);
    }//GEN-LAST:event_itemAutosActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAutos;
    private javax.swing.JMenuItem itemMarcas;
    private javax.swing.JMenuItem itemModelos;
    private javax.swing.JMenuItem itemRoles;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuGestion;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSistema;
    // End of variables declaration//GEN-END:variables

}
